### ISSUE TITLE
R.java NotFound and others

### ISSUE THREAD

**Issue by spianmo** [7hens/android-x2j#1]
#issue1:Pull下来的版本和自己的项目应用x2j后都出现R.java找不到的问题，测试版本：android-x2j -SNAPSHOT,Log如下

> java.lang.RuntimeException: javassist.NotFoundException: androidx2j.X2J
> 	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
> 	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
> 	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
> ........................省略...........................
> Caused by: javassist.NotFoundException: androidx2j.X2J
> 	at javassist.ClassPool.get(ClassPool.java:445)
> 	at androidx2j.X2JClassConverter$codeConverter$2.invoke(X2JClassConverter.kt:27)
> 	at androidx2j.X2JClassConverter$codeConverter$2.invoke(X2JClassConverter.kt:12)
> 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
> 	at androidx2j.X2JClassConverter.getCodeConverter(X2JClassConverter.kt)
> 	at androidx2j.X2JClassConverter.convert(X2JClassConverter.kt:62)
> 	at androidx2j.X2JTransform.transform(X2JTransform.kt:60)
> 	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
> 	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
> 	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
> 	... 77 more

#issue2:提议wiki增加关于'com.android.tools.build:gradle:3.5.1'版本问题，必须
<=com.android.tools.build:gradle:3.2.1版本，否则随机爆以下错误

> Unable to load class 'com.android.tools.r8.com.google.common.io.Files'.
> Possible causes for this unexpected error include:
> Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

**Comment by spianmo** [comment]
补充测试版本：android-x2j 1.1

**Comment by spianmo** [comment]
来自另一项目的类似报错,测试版本：android-x2j -SNAPSHOT
事实上此找不到的R.java实际位于：E:\TrackerProject\Terminal\build\generated\not_namespaced_r_class_sources\SpianmoRelease\r\com\trap\terminal\R.java
而不是：
E:\TrackerProject\Terminal\build\generated\ap_generated_sources\SpianmoRelease\out\com\trap\terminal\R.java 
附log:
> Task :Terminal:compileSpianmoReleaseJavaWithJavac
Gradle may disable incremental compilation as the following annotation processors are not incremental: x2c-apt-1.1.2.jar (com.zhangyue.we:x2c-apt:1.1.2), butterknife-compiler-10.1.0.jar (com.jakewharton:butterknife-compiler:10.1.0).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
java.io.FileNotFoundException: E:\TrackerProject\Terminal\build\generated\ap_generated_sources\SpianmoRelease\out\com\trap\terminal\R.java (系统找不到指定的路径。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.zhangyue.we.anoprocesser.xml.LayoutManager.getR(LayoutManager.java:264)
	at com.zhangyue.we.anoprocesser.xml.LayoutManager.setFiler(LayoutManager.java:88)
	at com.zhangyue.we.anoprocesser.XmlProcessor.init(XmlProcessor.java:34)
	at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.init(DelegatingProcessor.java:57)
	at org.gradle.api.internal.tasks.compile.processing.NonIncrementalProcessor.init(NonIncrementalProcessor.java:33)
	at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.init(DelegatingProcessor.java:57)
	at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.access$301(TimeTrackingProcessor.java:37)
	at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$4.create(TimeTrackingProcessor.java:88)
	...................中间省略..................
警告: 来自注释处理程序 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
注: tab_view.xml	->	com.zhangyue.we.x2c.layouts.X2C0_Dialog_File_Browser_Newfile.java
警告: 类型 '[bb, test]' 的文件未关闭; 将不针对这些类型进行注释处理
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: E:\TrackerProject\Terminal\src\main\java\com\trap\terminal\util\TempBufferList.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
2 个警告

**Comment by spianmo** [comment]
所有问题解决，最终排查为Kotlin版本问题，必须为1.3.31版本，在修改kotlin版本为1.3.31版本后一切问题消失，com.android.tools.build:gradle也无需修改，不过还是不明白为什么kotlin版本之间差异这么大
