### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by mainlxl** [7hens/android-x2j#7]
Caused by: java.lang.NullPointerException
        at com.zhangyue.we.anoprocesser.xml.LayoutManager.getRFile(LayoutManager.java:295)
        at com.zhangyue.we.anoprocesser.xml.LayoutManager.getR(LayoutManager.java:261)
        at com.zhangyue.we.anoprocesser.xml.LayoutManager.setFiler(LayoutManager.java:88)
        at com.zhangyue.we.anoprocesser.XmlProcessor.init(XmlProcessor.java:34)
        at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.init(incrementalProcessors.kt:36)
        at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.init(annotationProcessing.kt:207)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:691)
        ... 43 more

**Comment by 7hens** [comment]
请问你的 gradle 版本是多少？

**Comment by mainlxl** [comment]
7.3.3

**Comment by 7hens** [comment]
请问你的 X2C 版本是多少？

**Comment by YearnXie** [comment]
这个问题解决了吗？
